# Build stage

FROM golang:1.16 as build

WORKDIR /build

COPY . .

RUN go build -o cmd -ldflags '-linkmode external -extldflags "-static"' -tags netgo -installsuffix netgo

# Run stage

FROM alpine:latest

WORKDIR /app

COPY --from=build /build/cmd .

CMD ["/app/cmd"]