# Build stage

FROM golang:1.16 as build

WORKDIR /build

COPY . .

RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 go build -v -ldflags '-w -s' -o cmd

# Run stage

FROM alpine:latest

WORKDIR /app

COPY --from=build /build/cmd .

CMD ["/app/cmd"]